version: '3'

services:

  db:
    image: postgis/postgis
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - .env
    ports:
      - "555:5000"
    depends_on:
      - db
    command:  ["./wait-for-it.sh", "db:5432", "--", "flask", "--app", "api", "run", "--host=0.0.0.0"]
  
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "666:80"
    depends_on:
      - api
